version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: citizix_user
      POSTGRES_DB: citizix_db

volumes:
  postgres_data:
